### ISSUE TITLE
Хичээл оруулж өрсөлдөх 

### ISSUE THREAD

**Issue by maXim-coder** [ochko/prudge#12]
-Zorilgo: coder-n lessons bulang hugjuuleh.

-Hicheel devshuulj ursuldh temtseen. Sard 1 udaa. 1nees sariin tuhain suuliin udur hurtel.

-Temtseen helbereer zarlgadana. Sedev n sar bur uur. Admin & moderators yriltsaj bgad 1 sedev songono.(Coderuudiin ihenh heseg n sain meddggui sedvuud - stack,shortest path,jintei jingui graphic,graphaar guih arguud,algorithms of sorting.. etc.) Coderuud bichsn hicheelee bicheed upload oruulna.

-Oruulsn hicheeluudiig busag hicheeluud unshij like ugh, onoo uguh (1-5) geh meteer shalgaruulna.

-Oruulah hicheeliin shaardlaga ---- Kirilleer bichih, hamgiin deer n sedviin neriig oruulh. Het nurshihgui bh, het tovchlohgui bh, oilgomjtoi, jisheetei biy daalt bodlogotoi bh, ashiglasn material, web site-nha url-g oruulh

-Oruulah hicheelee haanas ch yaj ch olj bolno. Orchuulah hunii material ashiglah, nom huulah, hunii oruulhaar beldj bga hicheel hulgailah, huneer bichuulh geh met ymar ch arga baij bolno.(Temtseenii gol zorilgo n hugjuulh yvdl bolhoor ymar ch arga bsn hamaagui :p)

-Shagnal -- temtseen shig medali ugh, esvel tavan hoshuu ugh, onoo ugh (8 onoo-coderiin hamgiin undur onoo :p) geh met bj bolh ym.

-Ehnii 3 hicheeliig shalgaruulna.1t orsn hicheeliig coder deer oruulna.Ingehiin tuld ahiad 1 bulan nemeh, (algorithms gdg ch ym uu)

-Onoogoor shagnana geh argiig songovol 1t orvol 8 onoo, 2 - 4 onoo, 3 - 2 onoo. Deerees n medali esvl tavn hoshuu (ungu n odoogiinhtoi adilhan)

-Iim temtseen zohiovl garh ur dun: 
1.Hicheel oruulj bga coderuudiin bichih arga baril nemegdeh 
2.English sain meddggui coderuudad iluu ihiig surah bolomj olgoh, mongol nomnuud deer sain tailbarlaj bichigdeegui sedvuudiig songoh uchraas 
3.Bugd sain meddg bolchuul tsaashid zohiogdh temtseenuud ulam ursulduuntei sonirholtoi bolh 
4.Shineer bodoj ehelj bga coderuudad suraltsah bolomj neeh.(Tomoor helbel oln ulsiin olimpiadad amjilttai oroltsoh coderuud ulam olshiroh. :p) 
5.Hehe bodood bodood olsngui :))

-P.S: odoo shineer zohiogdh temtseen (bodlogo devshuuled ursuldh) 2 udaa mash amjilttai bolvl yriltsaj bgad bootsootoi bolgoy. Bodlogoo devshuuled, bootsoogo huraalgad ursuldvl sonirholtoi bizde :D 
Hervee bootsootoi bolchih ym bol hicheel devshuulh temtseen ch gsn mungun shagnaltai bolgoh bolomjtoi. Shine temtseenii shagnaliin sangaas 20 ymuu 30%-g n ene temtseenii shagnal bolgovl zugeer bh :)

**Comment by ochko** [comment]
Өөрдсөө хичээл бичсэнээс бараг интернэт дээр байгаа материалуудын линкийг цуглуулаад жагсаачихвал болох уу?

**Comment by alexbagirov** [comment]
What does it mean?

**Comment by ochko** [comment]
This issue is about adding new feature: To compete writing lessons.

**Comment by alexbagirov** [comment]
Oh, and are you going to add it?

**Comment by ochko** [comment]
I would like to implement rating for posts. And highest rates posts will shown at index page.
