### ISSUE TITLE
Contest's members are not shown

### ISSUE THREAD

**Issue by alexbagirov** [ochko/prudge#37]
If we're not logged in then we see an error when trying to look for contest's members.
![2015-05-17 21 24 16](https://cloud.githubusercontent.com/assets/6885864/7671169/2e977182-fcdb-11e4-9538-28d7cfa2ec8d.png)

**Comment by ochko** [comment]
That's intentional. Instead of "Error", we should show meaninful message like "Please login to see contest participants"

**Comment by alexbagirov** [comment]
Ok, will provide my idea of this message soon.

**Comment by ochko** [comment]
Fixed in 2bc3d2b0c6d864aa1221eceb858b564f6e9259b8
