### ISSUE TITLE
Message doesn't render when adding a test

### ISSUE THREAD

**Issue by alexbagirov** [ochko/prudge#43]
If we're going to add a new test and just hit "Save" without adding a files it shout show an error. There is a small problem with it...
![2015-05-17 22 19 52](https://cloud.githubusercontent.com/assets/6885864/7671304/daef3b16-fce2-11e4-89e1-c8eae94c7039.png)

**Comment by ochko** [comment]
Good catch.

**Comment by ochko** [comment]
Fixed in 82a0d4bc091b991ab5f23665d26e30c5e824ac3c
