### ISSUE TITLE
Pascal compilator error

### ISSUE THREAD

**Issue by alexbagirov** [ochko/prudge#44]
When submitting solution in pascal:
![2015-05-18 0 05 03](https://cloud.githubusercontent.com/assets/6885864/7671620/95b7d404-fcf1-11e4-8f97-11b8e94adbb0.png)

**Comment by alexbagirov** [comment]
It seems that I have an old version of it. Looking through.

**Comment by alexbagirov** [comment]
Oh, that's the problem with this version. It should be greater (for example, 2.4.6). I can't see them for Ubuntu. Do you have any ideas?

**Comment by ochko** [comment]
Can you put here your pascal source? So that I can reproduce the error message.

**Comment by alexbagirov** [comment]
I have Googled a little. It seems to be a common error which can be fixed by installing a newer version of Pascal (2.4.6 instead of current 2.4.4).

**Comment by ochko** [comment]
> Oh, that's the problem with this version. It should be greater (for example, 2.4.6). I can't see them for Ubuntu. Do you have any ideas?

On Ubuntu you can install free pascal 2.6:

`$ sudo apt-get install fp-compiler-2.6.2`

And test it manually on your server like:

`$ fpc solution.pas -osolution`

fpc has a lots of options. You can tweak compiler options in `config/languages.yml` if you want.
