### ISSUE TITLE
Logo link goes to 404

### ISSUE THREAD

**Issue by alexbagirov** [ochko/prudge#45]
We can see the name of the site at the top of every page. That is how it is declared in `app/views/layouts/application.haml`:
```haml
%a.brand{:href => "./index.html"}
```
When we click on it, we get 404 error. Maybe it would be better to change it for site index page?

**Comment by ochko** [comment]
Will fix it.

**Comment by ochko** [comment]
Fixed in 40d92f781f42c7176a513e49bcb13381aa5f7ec2
