### ISSUE TITLE
Timestamps processing

### ISSUE THREAD

**Issue by alexbagirov** [ochko/prudge#50]
If I am not mistaken Prudge now uses something like timeago.js to render timestamps and show something like "Contest will begin in {number} hours". Current templates for these strings are good to use in Mongolian translation but they are not acceptable for other languages that have different forms of words for different numbers (for example Russian and other cyrrillic languages). Maybe we can migrate to [Moment.js] (http://momentjs.com/) which seems to be easier to work with and has lots of translations?

**Comment by alexbagirov** [comment]
That problem can be found in config/locales/prudge.yml file which is not good to use for different languages :confused:

**Comment by ochko** [comment]
It will be easy if we user [rails-i18n](https://github.com/svenfuchs/rails-i18n) which support many languages including russian. But also we need to have language switch button.

**Comment by alexbagirov** [comment]
But what about switching to Moment? We will ve able to delete all translations associated with time and dates because it will do all for us.

**Comment by ochko** [comment]
`config/rails.yml` will be deleted once we start using *rails-i18n*. When I wrote prudge(many years ago) mn was not supported by *rails-i18n*. That's why there are date/time localizations for mn.

**Comment by alexbagirov** [comment]
Now I see :)

**Comment by alexbagirov** [comment]
But as I see rails-i18n is still for translations and it's not made special for working with time.

**Comment by ochko** [comment]
In rails-18n there is some missing localizations but time related localizations are pretty much complete.
